from odoo import models, fields, api, _
from odoo.exceptions import UserError
from dateutil.relativedelta import relativedelta
from datetime import date, timedelta
import calendar
import logging

_logger = logging.getLogger(__name__)

# -------------------------------------------------------------------
# Section 622 BGB - Statutory notice periods (employer -> employee)
# -------------------------------------------------------------------
BGB_622_PERIODS = [
    # (min_years, months_notice, german_label)
    (20, 7, '7 Monate zum Monatsende'),
    (15, 6, '6 Monate zum Monatsende'),
    (12, 5, '5 Monate zum Monatsende'),
    (10, 4, '4 Monate zum Monatsende'),
    (8, 3, '3 Monate zum Monatsende'),
    (5, 2, '2 Monate zum Monatsende'),
    (2, 1, '1 Monat zum Monatsende'),
]


class KwTermination(models.Model):
    _name = 'kw.termination'
    _description = 'Employee Termination Record'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'letter_date desc, id desc'
    _rec_name = 'display_name'

    # --- Core ---
    employee_id = fields.Many2one(
        'hr.employee', string='Mitarbeiter', required=True,
        tracking=True, ondelete='restrict',
    )
    company_id = fields.Many2one(
        'res.company', string='Unternehmen', required=True,
        default=lambda self: self.env.company, tracking=True,
    )
    termination_type = fields.Selection([
        ('ordentlich', 'Ordentliche K\u00fcndigung'),
        ('ordentlich_probezeit', 'Ordentliche K\u00fcndigung (Probezeit)'),
        ('fristlos', 'Fristlose K\u00fcndigung'),
        ('aufhebung', 'Aufhebungsvertrag'),
        ('bestaetigung', 'K\u00fcndigungsbest\u00e4tigung'),
    ], string='Art', required=True, tracking=True)
    state = fields.Selection([
        ('draft', 'Entwurf'),
        ('confirmed', 'Best\u00e4tigt'),
        ('signed', 'Unterschrieben'),
        ('delivered', 'Zugestellt'),
        ('archived', 'Archiviert'),
        ('cancelled', 'Storniert'),
    ], string='Status', default='draft', required=True, tracking=True)

    # --- Dates & notice period ---
    letter_date = fields.Date(
        string='Datum des Schreibens', default=fields.Date.today,
        required=True, tracking=True,
    )
    receipt_date = fields.Date(
        string='Zugangsdatum',
        help='Datum, an dem der Arbeitnehmer das Schreiben erh\u00e4lt',
    )
    calc_method = fields.Selection([
        ('bgb', '\u00a7 622 BGB gesetzlich'),
        ('receipt', 'Ab Zugang'),
    ], string='Berechnungsmethode', default='bgb', required=True)
    notice_period_text = fields.Char(
        string='K\u00fcndigungsfrist', compute='_compute_dates', store=True,
    )
    last_working_day = fields.Date(
        string='Letzter Arbeitstag', compute='_compute_dates',
        store=True, readonly=False, tracking=True,
    )

    # --- Employee info (snapshot) ---
    employee_name = fields.Char(
        related='employee_id.name', store=True, string='Name',
    )
    employee_street = fields.Char(string='Stra\u00dfe')
    employee_city = fields.Char(string='Stadt')
    employee_zip = fields.Char(string='PLZ')
    employee_start_date = fields.Date(
        string='Besch\u00e4ftigungsbeginn', compute='_compute_employee_info', store=True,
    )
    tenure_years = fields.Float(
        string='Betriebszugeh\u00f6rigkeit (Jahre)',
        compute='_compute_employee_info', store=True,
    )
    in_probation = fields.Boolean(
        string='In Probezeit', compute='_compute_employee_info', store=True,
    )
    probation_end = fields.Date(
        string='Probezeit bis', compute='_compute_employee_info', store=True,
    )

    # --- Fristlose K\u00fcndigung ---
    incident_date = fields.Date(string='Datum des Vorfalls')
    incident_description = fields.Text(string='Beschreibung (intern)')

    # --- Aufhebungsvertrag ---
    include_severance = fields.Boolean(string='Abfindung')
    severance_amount = fields.Float(string='Abfindungsbetrag (EUR)')
    garden_leave = fields.Boolean(string='Freistellung')

    # --- K\u00fcndigungsbest\u00e4tigung ---
    resignation_received_date = fields.Date(string='K\u00fcndigung erhalten am')

    # --- PDF + Signature (managed by portal, stored here) ---
    pdf_attachment_id = fields.Many2one(
        'ir.attachment', string='PDF',
        help='Generated by the portal',
    )
    signed_pdf_attachment_id = fields.Many2one(
        'ir.attachment', string='Unterschriebenes PDF',
    )

    # --- Delivery tracking ---
    delivery_method = fields.Selection([
        ('einschreiben_rueckschein', 'Einschreiben mit R\u00fcckschein'),
        ('einwurf_einschreiben', 'Einwurf-Einschreiben'),
        ('personal', 'Pers\u00f6nliche \u00dcbergabe'),
        ('bote', 'Bote (mit Zeuge)'),
    ], string='Zustellungsart', tracking=True)
    delivery_date = fields.Date(string='Zustelldatum', tracking=True)
    delivery_tracking_number = fields.Char(string='Sendungsnummer')
    delivery_witness = fields.Char(string='Zeuge')
    delivery_confirmed = fields.Boolean(string='Zustellung best\u00e4tigt', tracking=True)
    delivery_confirmed_date = fields.Date(string='Best\u00e4tigt am')
    delivery_proof_attachment_id = fields.Many2one(
        'ir.attachment', string='Zustellnachweis',
    )
    delivery_notes = fields.Text(string='Anmerkungen')

    # --- Accountant ---
    sent_to_accountant = fields.Boolean(string='An Steuerberater gesendet')
    sent_to_accountant_date = fields.Datetime(string='Gesendet am')

    display_name = fields.Char(compute='_compute_display_name', store=True)

    # =================================================================
    # Computed fields
    # =================================================================
    @api.depends('employee_name', 'termination_type', 'letter_date')
    def _compute_display_name(self):
        labels = dict(self._fields['termination_type'].selection)
        for rec in self:
            parts = [rec.employee_name or 'Neu']
            if rec.termination_type:
                parts.append(labels.get(rec.termination_type, ''))
            if rec.letter_date:
                parts.append(str(rec.letter_date))
            rec.display_name = ' \u2013 '.join(parts)

    @api.depends('employee_id', 'letter_date')
    def _compute_employee_info(self):
        for rec in self:
            emp = rec.employee_id
            if not emp:
                rec.employee_start_date = False
                rec.tenure_years = 0
                rec.in_probation = False
                rec.probation_end = False
                continue

            contract = self.env['hr.contract'].search([
                ('employee_id', '=', emp.id),
                ('state', '=', 'open'),
            ], limit=1, order='date_start asc')
            start = contract.date_start if contract else False
            rec.employee_start_date = start

            ref = rec.letter_date or date.today()
            if start:
                d = relativedelta(ref, start)
                rec.tenure_years = round(d.years + d.months / 12.0, 1)
            else:
                rec.tenure_years = 0

            prob_end = contract.trial_date_end if contract else False
            rec.probation_end = prob_end
            rec.in_probation = bool(prob_end and ref <= prob_end)

    @api.depends(
        'termination_type', 'calc_method', 'letter_date', 'receipt_date',
        'employee_start_date', 'tenure_years', 'in_probation',
        'resignation_received_date',
    )
    def _compute_dates(self):
        for rec in self:
            if not rec.termination_type or not rec.letter_date:
                rec.notice_period_text = ''
                rec.last_working_day = False
                continue

            ttype = rec.termination_type
            if ttype == 'fristlos':
                rec.notice_period_text = 'Sofort (fristlos)'
                rec.last_working_day = rec.letter_date

            elif ttype == 'aufhebung':
                rec.notice_period_text = 'Einvernehmlich'
                # last_working_day set manually

            elif ttype == 'bestaetigung':
                ref = rec.resignation_received_date or rec.letter_date
                rec.notice_period_text = '4 Wochen zum 15. oder Monatsende'
                rec.last_working_day = self._snap_15_or_end(ref + timedelta(days=28))

            elif ttype in ('ordentlich', 'ordentlich_probezeit'):
                if rec.in_probation or ttype == 'ordentlich_probezeit':
                    base = (rec.receipt_date if rec.calc_method == 'receipt' and rec.receipt_date
                            else rec.letter_date)
                    rec.notice_period_text = '2 Wochen (Probezeit)'
                    rec.last_working_day = base + timedelta(days=14)
                else:
                    rec.notice_period_text, rec.last_working_day = \
                        self._calc_bgb622(rec)

    def _calc_bgb622(self, rec):
        """Calculate notice period per Par. 622 BGB."""
        tenure = rec.tenure_years or 0
        base = (rec.receipt_date if rec.calc_method == 'receipt' and rec.receipt_date
                else rec.letter_date)

        for min_years, months, label in BGB_622_PERIODS:
            if tenure >= min_years:
                earliest = base + relativedelta(months=months)
                return (label, self._snap_month_end(earliest))

        # Default: 4 weeks to 15th or month-end
        earliest = base + timedelta(days=28)
        return ('4 Wochen zum 15. oder Monatsende', self._snap_15_or_end(earliest))

    @staticmethod
    def _snap_15_or_end(d):
        """Snap date to next 15th or end-of-month."""
        fif = d.replace(day=15)
        if fif >= d:
            return fif
        last = calendar.monthrange(d.year, d.month)[1]
        eom = d.replace(day=last)
        if eom >= d:
            return eom
        nxt = d + relativedelta(months=1)
        return nxt.replace(day=15)

    @staticmethod
    def _snap_month_end(d):
        """Snap date to end of month."""
        last = calendar.monthrange(d.year, d.month)[1]
        eom = d.replace(day=last)
        if eom >= d:
            return eom
        nxt = d + relativedelta(months=1)
        last = calendar.monthrange(nxt.year, nxt.month)[1]
        return nxt.replace(day=last)

    # =================================================================
    # Onchange
    # =================================================================
    @api.onchange('employee_id')
    def _onchange_employee_id(self):
        if self.employee_id:
            emp = self.employee_id
            self.employee_street = emp.private_street or ''
            self.employee_city = emp.private_city or ''
            self.employee_zip = emp.private_zip or ''
            self.company_id = emp.company_id
